# Generated by Django 4.0.2 on 2022-03-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_category_organisation_alter_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('company', models.CharField(default=None, max_length=100)),
                ('post', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=100)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'Whatsapp'), ('polleen', 'Polleen')], default='Polleen', max_length=100)),
                ('leisure', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('website', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('other_social_media', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('invited_by', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
            ],
        ),
    ]
