# Generated by Django 4.0.2 on 2022-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_invitedlead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedlead',
            name='communication_preference',
        ),
        migrations.RemoveField(
            model_name='invitedlead',
            name='leisure',
        ),
    ]
