# Generated by Django 4.0.2 on 2022-05-26 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('author_1', models.CharField(default=None, max_length=100)),
                ('author_2', models.CharField(default=None, max_length=100)),
                ('document', models.FileField(upload_to='docs/files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif', 'docx', 'pptx', 'pdf'])])),
                ('document_suplementaire', models.FileField(blank=True, default=None, null=True, upload_to='docs/files/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
