# Generated by Django 4.0.2 on 2022-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('post', models.CharField(default=None, max_length=100)),
                ('company', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('url_profile', models.URLField()),
            ],
        ),
    ]
